default_language_version:
  python: python3
repos:
  - repo: https://github.com/Seeefo/manage-commit-msg.git
    rev: 1.0.3
    hooks:
      - id: save-commit-msg
      - id: restore-commit-msg

  - repo: https://github.com/jorisroovers/gitlint.git
    rev: v0.18.0
    hooks:
      - id: gitlint

  - repo: https://github.com/ambv/black.git
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8.git
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-logging-format, "importlib-metadata<5.0"]

  - repo: https://github.com/pycqa/isort.git
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
